project_id = "gljsifkjwkubxaqgxxul"

[functions.sync-whatsapp-conversations]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.kiwify-sync]
verify_jwt = false

[functions.followup-ai]
verify_jwt = false

[functions.followup-check-inactive]
verify_jwt = false

[functions.manage-system-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.support-ai-agent]
verify_jwt = false
