project_id = "gljsifkjwkubxaqgxxul"

[functions.sync-whatsapp-conversations]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.kiwify-sync]
verify_jwt = false

[functions.followup-ai]
verify_jwt = false

[functions.followup-check-inactive]
verify_jwt = false

[functions.manage-system-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.support-ai-agent]
verify_jwt = false

[functions.transcribe-browser-audio]
verify_jwt = false

[functions.notify-new-user]
verify_jwt = false

[functions.process-pending-support-ai]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.send-welcome-sequence]
verify_jwt = false

[functions.sync-whatsapp-statuses]
verify_jwt = false

[functions.sync-whatsapp-profile-pictures]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.send-task-reminders]
verify_jwt = false
