
INSERT INTO public.help_articles (category_id, slug, title, summary, content, position, published) VALUES

('171e5c2b-9266-451b-acc5-fbe8b2a3fad3', 'trial-como-funciona', 'Como funciona o teste grátis de 15 dias',
 'Você tem 15 dias para testar tudo sem pagar nada.',
$$<h2>Os 15 dias de teste</h2><p>Ao criar sua conta no Theo IA, você ganha automaticamente <strong>15 dias gratuitos</strong> com acesso a todas as funcionalidades — IA respondendo, CRM, agendamentos, base de conhecimento, equipe e relatórios.</p><h2>Como saber quanto tempo falta</h2><p>No topo do painel aparece uma barra amarela mostrando quantos dias restam do seu teste. Quando faltarem poucos dias, o aviso fica em destaque.</p><h2>O que acontece quando o teste acaba</h2><ul><li>O acesso à plataforma é bloqueado automaticamente.</li><li>A IA para de responder seus clientes.</li><li>Seus dados ficam guardados — basta assinar para liberar tudo de novo.</li></ul><h2>Como assinar antes do fim do teste</h2><p>Clique em <strong>"Assinar agora"</strong> no banner amarelo ou vá em <strong>Assinaturas</strong> no menu lateral. Você é redirecionado para o checkout seguro da Kiwify.</p><h2>Posso ganhar mais dias?</h2><p>Sim. Em casos especiais o suporte pode estender seu teste. Fale com a gente pelo WhatsApp <strong>+55 47 99129-3662</strong>.</p>$$, 10, true),

('171e5c2b-9266-451b-acc5-fbe8b2a3fad3', 'como-assinar', 'Como assinar seu plano',
 'Passo a passo do checkout via Kiwify.',
$$<h2>Passo 1 — Escolha seu plano</h2><p>No menu lateral, clique em <strong>Assinaturas</strong>. Compare Basic e Pro, e escolha entre Mensal ou Anual.</p><h2>Passo 2 — Clique em "Assinar"</h2><p>Você é redirecionado para o checkout seguro da <strong>Kiwify</strong>, nossa parceira de pagamentos.</p><h2>Passo 3 — Preencha seus dados</h2><ul><li>Use o <strong>mesmo e-mail</strong> que você cadastrou no Theo IA — é assim que liberamos seu acesso automaticamente.</li><li>Escolha cartão de crédito, Pix ou boleto.</li></ul><h2>Passo 4 — Confirme o pagamento</h2><p>Após a confirmação, sua conta é liberada em até <strong>5 minutos</strong>. Você recebe um e-mail de confirmação e o banner amarelo desaparece.</p><h2>Não foi liberado automaticamente?</h2><p>Em raros casos pode demorar. Se passar de 30 minutos, fale com o suporte pelo WhatsApp <strong>+55 47 99129-3662</strong> com o comprovante.</p>$$, 11, true),

('171e5c2b-9266-451b-acc5-fbe8b2a3fad3', 'gerenciar-assinatura', 'Gerenciar ou cancelar assinatura',
 'Como atualizar cartão, mudar plano ou cancelar.',
$$<h2>Onde gerenciar sua assinatura</h2><p>Toda a parte de cobrança fica no painel da <strong>Kiwify</strong>. Acesse pelo e-mail de confirmação ou em <strong>app.kiwify.com.br</strong> com o mesmo e-mail.</p><h2>Atualizar cartão de crédito</h2><ol><li>Entre na sua conta Kiwify.</li><li>Vá em <strong>Minhas assinaturas</strong>.</li><li>Selecione o Theo IA e clique em <strong>Atualizar forma de pagamento</strong>.</li></ol><h2>Cancelar assinatura</h2><ol><li>No painel Kiwify, abra <strong>Minhas assinaturas</strong>.</li><li>Clique em <strong>Cancelar assinatura</strong>.</li><li>Seu acesso continua até o fim do período já pago.</li></ol><h2>Mudar de plano</h2><p>Para trocar entre Basic, Pro, Mensal ou Anual, fale com nosso suporte pelo WhatsApp <strong>+55 47 99129-3662</strong> — fazemos a troca proporcional para você.</p><h2>Reembolso</h2><p>Garantia de 7 dias após a primeira compra, conforme o Código de Defesa do Consumidor. Após esse prazo, não há reembolso de mensalidades já pagas.</p>$$, 12, true),

('15e1fc19-19d5-47b8-8931-508d807a162f', 'convidar-novo-membro', 'Convidando um novo membro para a equipe',
 'Adicione vendedores e atendentes à sua conta.',
$$<h2>O que é a equipe</h2><p>A equipe permite que <strong>vários atendentes</strong> usem o Theo IA dentro da mesma conta — cada um com login próprio, mas compartilhando contatos, conversas, CRM e agendamentos.</p><blockquote>Recurso disponível no <strong>plano Pro</strong>.</blockquote><h2>Como convidar alguém</h2><ol><li>No menu lateral, clique em <strong>Configurações</strong>.</li><li>Abra a aba <strong>Equipe</strong>.</li><li>Clique em <strong>Convidar membro</strong>.</li><li>Preencha nome, e-mail e a senha provisória que ele vai usar no primeiro acesso.</li><li>Defina a função (Atendente ou Gerente) e marque as permissões.</li><li>Clique em <strong>Salvar</strong>.</li></ol><h2>O que acontece em seguida</h2><ul><li>O novo membro recebe acesso imediato com o e-mail e senha que você definiu.</li><li>No primeiro login ele é obrigado a trocar a senha.</li><li>Ele só vê o que as permissões deixarem.</li></ul>$$, 10, true),

('15e1fc19-19d5-47b8-8931-508d807a162f', 'roleta-leads', 'Distribuindo leads com a Roleta',
 'Reparta automaticamente novos contatos entre a equipe.',
$$<h2>O que é a Roleta</h2><p>A Roleta distribui <strong>automaticamente</strong> os novos contatos do WhatsApp entre os membros da sua equipe, em rodízio. Ninguém fica sobrecarregado e ninguém fica sem lead.</p><h2>Como ativar</h2><ol><li>Vá em <strong>Configurações → Roleta</strong>.</li><li>Ative a opção <strong>Distribuição automática</strong>.</li><li>Marque os membros que devem entrar na roleta.</li><li>Defina se a roleta deve respeitar o horário de cada atendente.</li><li>Salve.</li></ol><h2>Como funciona na prática</h2><ul><li>Toda vez que um <strong>contato novo</strong> manda mensagem, ele é atribuído ao próximo membro da fila.</li><li>O membro vê a conversa aparecer no painel dele e recebe uma notificação.</li><li>Se for um contato já existente, ele vai direto para o atendente que já cuida dele.</li></ul><h2>Pausar um membro</h2><p>Quando alguém estiver de folga ou em reunião, basta desmarcá-lo na lista da roleta. Ele volta a receber leads quando você reativar.</p>$$, 11, true),

('4789f8cd-5038-4817-a0a2-e39277d220dc', 'tipos-agendamento', 'Criando tipos de agendamento',
 'Defina os serviços que sua IA pode agendar.',
$$<h2>O que é um "tipo de agendamento"</h2><p>É cada serviço diferente que você oferece. Por exemplo: <em>Avaliação</em>, <em>Consulta</em>, <em>Procedimento</em>, <em>Reunião comercial</em>. Cada tipo tem sua própria duração, horários e dias da semana.</p><h2>Como criar</h2><ol><li>Menu lateral → <strong>Agendamentos</strong> → aba <strong>Configurações</strong>.</li><li>Clique em <strong>Novo tipo</strong>.</li><li>Preencha:<ul><li><strong>Nome</strong> (ex: Avaliação Inicial)</li><li><strong>Duração</strong> em minutos</li><li><strong>Dias da semana</strong> que esse serviço acontece</li><li><strong>Horário de início e fim</strong></li><li><strong>Quantos atendimentos no mesmo horário</strong> (1 = exclusivo)</li></ul></li><li>Salve.</li></ol><h2>Por que isso importa para a IA</h2><p>A IA <strong>só oferece para o cliente os horários que existem em algum tipo ativo</strong>. Se você não criou nenhum tipo, a IA não consegue agendar.</p><h2>Desativar sem apagar</h2><p>Se quiser pausar um serviço (ex: férias), desative o tipo em vez de apagar. Os agendamentos antigos continuam, mas a IA para de oferecer aquele horário.</p>$$, 10, true),

('4789f8cd-5038-4817-a0a2-e39277d220dc', 'confirmacao-2h-antes', 'Fluxo de confirmação 2 horas antes',
 'A IA confirma automaticamente os agendamentos.',
$$<h2>Como funciona</h2><p>Duas horas antes do horário marcado, a IA reabre a conversa com o cliente para uma <strong>confirmação final</strong>:</p><ul><li>Se o cliente confirmar → o agendamento fica como <strong>Confirmado</strong>.</li><li>Se cancelar → o status vira <strong>Cancelado</strong> e o horário volta a ficar livre.</li><li>Se não responder → você recebe uma notificação para decidir.</li></ul><h2>Exemplo de mensagem</h2><blockquote>"Oi, [Nome]! Passando para confirmar nosso atendimento hoje às 14h. Posso confirmar sua presença?"</blockquote><h2>Por que isso ajuda</h2><ul><li>Reduz drasticamente o número de "não-comparecimentos" (no-show).</li><li>Libera horários cancelados antes da hora — você consegue encaixar outro cliente.</li><li>Você sabe com antecedência o que esperar do dia.</li></ul><h2>Notificações</h2><p>Em <strong>Configurações → Notificações</strong>, cadastre os números que devem receber aviso de confirmações e cancelamentos.</p>$$, 11, true),

('4789f8cd-5038-4817-a0a2-e39277d220dc', 'tarefas-crm', 'Tarefas vinculadas a oportunidades',
 'Não esqueça de nenhum follow-up de venda.',
$$<h2>O que são tarefas</h2><p>Dentro do CRM, cada oportunidade pode ter <strong>tarefas com data e responsável</strong>. Por exemplo: "Ligar para o cliente sexta-feira às 10h" ou "Enviar proposta até amanhã".</p><h2>Como criar uma tarefa</h2><ol><li>Abra a oportunidade no <strong>CRM</strong>.</li><li>Role até a seção <strong>Tarefas</strong>.</li><li>Clique em <strong>Nova tarefa</strong>.</li><li>Defina título, descrição, data, hora e responsável.</li><li>Salve.</li></ol><h2>Lembrete automático</h2><p>Quando faltam alguns minutos para a hora da tarefa, o responsável recebe uma notificação no WhatsApp avisando.</p><h2>Painel de tarefas</h2><p>Em <strong>Tarefas</strong> no menu lateral você vê todas as tarefas em aberto, atrasadas e concluídas — com filtros por responsável, data e status.</p>$$, 12, true),

('0a045795-19d3-4b07-a579-97f7804e6bff', 'pareamento-codigo', 'Conectando o WhatsApp por código de pareamento',
 'Alternativa ao QR Code: digite um código de 8 dígitos.',
$$<h2>Quando usar o código de pareamento</h2><p>Use quando o QR Code não estiver funcionando, quando você não conseguir abrir a câmera do celular ou quando estiver conectando por outro aparelho.</p><h2>Passo a passo</h2><ol><li>No Theo IA, vá em <strong>WhatsApp</strong> no menu lateral.</li><li>Clique em <strong>Conectar com código</strong>.</li><li>Digite o número do WhatsApp que você quer conectar (com DDD).</li><li>O sistema gera um <strong>código de 8 dígitos</strong> que aparece na tela.</li><li>No celular, abra o WhatsApp → <strong>Aparelhos conectados</strong> → <strong>Conectar um aparelho</strong> → <strong>Conectar com número de telefone</strong>.</li><li>Digite o código de 8 dígitos exibido no Theo IA.</li><li>Pronto — a conexão é feita em alguns segundos.</li></ol><h2>O código expirou</h2><p>O código tem validade curta. Se passar muito tempo, basta clicar em <strong>Gerar novo código</strong>.</p><h2>Já estava conectado e caiu</h2><p>Se a sessão antiga ainda estiver ativa, o sistema recria a instância antes de gerar o novo código — isso evita conflitos.</p>$$, 10, true),

('0a045795-19d3-4b07-a579-97f7804e6bff', 'audio-imagem-ia', 'IA que entende áudios e imagens',
 'Seu cliente pode mandar foto ou áudio — a IA entende.',
$$<h2>O que a IA consegue interpretar</h2><ul><li><strong>Áudios</strong> → transcritos automaticamente em texto e usados como contexto da conversa.</li><li><strong>Imagens</strong> → analisadas visualmente (ex: foto de produto, conta de luz, documento) e descritas para a IA antes de responder.</li></ul><h2>Como funciona por trás</h2><p>Quando o cliente envia um áudio, ele passa por transcrição via <strong>Groq Whisper</strong>. Quando envia uma imagem, ela passa por <strong>Gemini Vision</strong>. O conteúdo extraído entra no histórico e a IA responde com base nele.</p><h2>Exemplos práticos</h2><ul><li>Cliente manda áudio explicando um sintoma → IA agenda a consulta certa.</li><li>Cliente envia foto da conta de luz → IA já capta o consumo e segue o atendimento.</li><li>Cliente manda foto do documento → IA confirma o cadastro.</li></ul><h2>Custo</h2><p>Cada áudio transcrito e cada imagem analisada consome <strong>créditos de IA</strong>. Você acompanha o gasto em <strong>Configurações → Créditos</strong>.</p>$$, 11, true),

('4d98192c-5bea-4ddb-923b-e3cb23340ffd', 'ativar-voz-elevenlabs', 'Ativando respostas em voz (ElevenLabs)',
 'Faça a IA responder com áudios reais em vez de texto.',
$$<h2>O que muda com a voz ativada</h2><p>Em vez de mandar texto, a IA <strong>grava áudios em voz natural</strong> usando o ElevenLabs e envia direto no WhatsApp do cliente. A experiência fica mais humana.</p><blockquote>Recurso disponível em planos pagos com créditos de voz habilitados.</blockquote><h2>Como ativar</h2><ol><li>Menu → <strong>Agente IA</strong> → aba <strong>Geral</strong>.</li><li>Localize <strong>Respostas em áudio (voz)</strong>.</li><li>Ative o switch.</li><li>Salve.</li></ol><h2>Como a IA decide entre texto e áudio</h2><p>A IA <strong>espelha o formato do cliente</strong>: se ele mandou áudio, ela responde com áudio; se mandou texto, ela responde com texto. Isso deixa a conversa natural.</p><h2>Limites técnicos</h2><ul><li>Cada trecho de áudio é limitado a ~600 caracteres.</li><li>Respostas longas são quebradas em vários áudios curtos.</li><li>Use voz só se o seu plano ElevenLabs for pago — o gratuito bloqueia chamadas vindas de servidores em nuvem.</li></ul><h2>Quanto consome</h2><p>Cada caractere falado conta como uso de voz e desconta do saldo de créditos. Acompanhe em <strong>Configurações → Créditos</strong>.</p>$$, 10, true),

('4d98192c-5bea-4ddb-923b-e3cb23340ffd', 'creditos-ia', 'Como funcionam os créditos de IA',
 'Entenda o saldo, os custos e como recarregar.',
$$<h2>Por que existem créditos</h2><p>Cada vez que a IA pensa, transcreve um áudio, analisa uma imagem ou fala em voz, ela consome processamento de modelos pagos (Gemini, Groq, ElevenLabs). Os créditos cobrem esse custo.</p><h2>O que consome créditos</h2><ul><li><strong>Resposta em texto</strong> — baixo custo, paga por tokens de entrada e saída.</li><li><strong>Transcrição de áudio</strong> — paga por minuto de áudio.</li><li><strong>Análise de imagem</strong> — paga por imagem.</li><li><strong>Resposta em voz</strong> — paga por caractere falado.</li></ul><h2>Onde ver seu saldo</h2><p>Vá em <strong>Configurações → Créditos</strong>. Você vê saldo atual, total já consumido e histórico de cada cobrança.</p><h2>Recarregar</h2><p>Recargas são feitas pelo suporte. Fale com a gente no WhatsApp <strong>+55 47 99129-3662</strong> informando o valor desejado e a forma de pagamento.</p><h2>O que acontece se zerar</h2><p>A IA para de responder até a próxima recarga. As mensagens dos clientes continuam chegando — você ou sua equipe podem responder na mão.</p>$$, 11, true),

('4d98192c-5bea-4ddb-923b-e3cb23340ffd', 'followup-6-dias', 'Follow-up automático de 6 dias (12 etapas)',
 'A IA recupera clientes que sumiram, em rodadas inteligentes.',
$$<h2>O que é o follow-up automático</h2><p>Quando um cliente para de responder, a IA <strong>volta a falar com ele sozinha</strong>, ao longo de até <strong>6 dias</strong>, distribuídos em <strong>12 mensagens</strong> com gatilhos de venda diferentes (curiosidade, prova social, escassez, oferta etc.).</p><h2>Como ativar</h2><ol><li>Menu → <strong>Follow-up</strong>.</li><li>Ative o switch <strong>Follow-up automático</strong>.</li><li>Defina:<ul><li><strong>Inatividade</strong> — quanto tempo sem resposta antes de começar (ex: 24h)</li><li><strong>Janela da manhã</strong> e <strong>janela da tarde</strong> — só dispara nesses horários</li><li><strong>Ferramentas de barganha</strong> — descontos, brindes ou bônus que a IA pode usar</li><li><strong>Excluir handoffs</strong> — não mexer com clientes que já foram para atendimento humano</li></ul></li><li>Salve.</li></ol><h2>O que acontece dia a dia</h2><ul><li><strong>Dia 1 a 2</strong> — toques leves para reabrir conversa</li><li><strong>Dia 3 a 4</strong> — prova social e quebra de objeção</li><li><strong>Dia 5 a 6</strong> — oferta final, escassez e despedida</li></ul><h2>Quando a IA para sozinha</h2><ul><li>Cliente respondeu → a IA volta ao atendimento normal.</li><li>Cliente comprou ou foi para "Vendido" no CRM.</li><li>Atendente humano respondeu na conversa.</li></ul>$$, 12, true),

('f097f7f0-5c54-4309-9d49-dc2a40c24087', 'abrir-ticket-suporte', 'Abrindo um ticket de suporte',
 'Como pedir ajuda quando algo não funciona.',
$$<h2>Quando abrir um ticket</h2><ul><li>A IA está respondendo errado e o ajuste do prompt não resolveu</li><li>O WhatsApp não conecta de jeito nenhum</li><li>Você precisa de um ajuste técnico (créditos, plano, dias extras)</li><li>Bug ou comportamento estranho na plataforma</li></ul><h2>Canais de suporte</h2><h3>1. WhatsApp direto</h3><p>O caminho mais rápido. Mande mensagem para <strong>+55 47 99129-3662</strong>. Você fala com nosso atendimento (humano + IA Theo) 24h.</p><h3>2. Botão de ajuda dentro da plataforma</h3><ol><li>Em qualquer tela, clique no botão de <strong>ajuda</strong>.</li><li>Descreva o problema com o máximo de detalhes.</li><li>Anexe prints se possível.</li><li>Envie.</li></ol><p>Seu ticket entra na fila do admin e você recebe a resposta no WhatsApp do sistema.</p><h2>Dicas para ser respondido mais rápido</h2><ul><li>Diga o e-mail da sua conta.</li><li>Diga o número do cliente envolvido (se for caso de IA).</li><li>Cole a mensagem da IA que ficou errada — facilita ajustar o prompt.</li><li>Mande print do erro, se houver.</li></ul>$$, 10, true),

('f097f7f0-5c54-4309-9d49-dc2a40c24087', 'dashboard-metricas', 'Entendendo o Dashboard',
 'KPIs, funil de conversão, metas e desempenho da equipe.',
$$<h2>O que o Dashboard mostra</h2><p>O Dashboard é a tela inicial após o login. Ele resume <strong>como seu negócio está indo agora</strong>, em tempo real, com base nas conversas, agendamentos e oportunidades do CRM.</p><h2>Cards principais (KPIs)</h2><ul><li><strong>Conversas ativas</strong> — quantos clientes estão em atendimento</li><li><strong>Tempo médio de resposta</strong> — quanto a IA e a equipe demoram para responder</li><li><strong>Tempo médio de atendimento</strong> — duração média de cada conversa</li><li><strong>Atendentes online</strong> — quem da equipe está conectado agora</li></ul><h2>Funil de conversão</h2><p>Mostra quantos contatos passaram por cada etapa do CRM (de "Novo lead" até "Vendido"), com a <strong>taxa de conversão</strong> entre uma fase e a próxima. Ajuda a achar o gargalo.</p><h2>Metas vs. realizado</h2><p>Compara o que a equipe está entregando contra a meta definida. Se você não definiu meta, o gráfico fica vazio.</p><h2>Desempenho por vendedor</h2><p>Tabela com cada membro da equipe, número de conversas atendidas, agendamentos criados e vendas fechadas no período.</p><h2>Filtros</h2><p>No topo, escolha o período (hoje, semana, mês, personalizado) e, se quiser, filtre por atendente. Os números atualizam na hora.</p>$$, 11, true);
